# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpotifyClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for SpotifyClone
  pod 'SDWebImage', :modular_headers => true
  pod 'Appirater', :modular_headers => true
  pod 'Firebase/Analytics', :modular_headers => true
end
